sudo: false
install: true

addons:
  sonarcloud:
    organization: "sukenda"
    token:
      secure: "48b60c91a018dbac0883c27b39367f612e8d2ec1"

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean verify sonar:sonar -Pcoverage

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
