server:
  port: 8081
  error:
    whitelabel:
      enabled: false

spring:
  main:
    banner-mode: off
  application:
    name: SPRING BOILERPLATE (LOCAL)
  data:
    mongodb:
      port: 27017
      database: boilerplate-spring
      username: boilerplate
      password: boilerplate
