GET http://localhost:8081/roles
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9URUFDSEVSIl0sInN1YiI6InN1a2VuZGEiLCJpYXQiOjE1OTU0OTE5NTAsImV4cCI6MTU5NTUyMDc1MH0.ittlok9wo97FDlALaKaZ8s_ZnDEnVbL0vqa9Pg2Avnql3tiw8qxccqdzL9_Pc5cyNyeYTeqLVmOmPFQxYlJU0w

###
GET http://localhost:8081/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9URUFDSEVSIl0sInN1YiI6InN1a2VuZGEiLCJpYXQiOjE1OTU0OTE5NTAsImV4cCI6MTU5NTUyMDc1MH0.ittlok9wo97FDlALaKaZ8s_ZnDEnVbL0vqa9Pg2Avnql3tiw8qxccqdzL9_Pc5cyNyeYTeqLVmOmPFQxYlJU0w

###
GET http://localhost:8081/users/5f193f6fde32d3373b426f44
Accept: application/json

###
POST http://localhost:8081/do-login
Content-Type: application/json

{
  "username": "sukenda",
  "password": "sukenda"
}

###
POST http://localhost:8081/do-register
Content-Type: application/json

{
  "username": "simak-ma",
  "password": "simak-ma",
  "roles": [
    "ROLE_ADMIN",
    "ROLE_TEACHER"
  ]
}
###
POST http://localhost:8081/refresh-token?token=eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9URUFDSEVSIl0sInN1YiI6InN1a2VuZGEiLCJpYXQiOjE1OTYwOTc3NTUsImV4cCI6MTU5ODk3Nzc1NX0.qw2lQfxRBNU8G3TMYRWHNcCDP7DWmBp91uAWIaBCvPUJtpkFBkMWg8K4squGs3DOl2Zl13HW6FXMB5NZfTN-t
Content-Type: application/json
