GET http://localhost:8080/users/id
Accept: application/json

###
POST http://localhost:8080/do-login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "roles": ["ROLE_ADMIN","ROLE_USER"]
}

###
POST http://localhost:8080/do-register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "roles": ["ROLE_USER","ROLE_ADMIN"]
}
