GET http://localhost:8081/roles
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9URUFDSEVSIl0sInN1YiI6InN1a2VuZGEiLCJpYXQiOjE1OTU0OTE5NTAsImV4cCI6MTU5NTUyMDc1MH0.ittlok9wo97FDlALaKaZ8s_ZnDEnVbL0vqa9Pg2Avnql3tiw8qxccqdzL9_Pc5cyNyeYTeqLVmOmPFQxYlJU0w

###
GET http://localhost:8081/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9URUFDSEVSIl0sInN1YiI6InN1a2VuZGEiLCJpYXQiOjE1OTU0OTE5NTAsImV4cCI6MTU5NTUyMDc1MH0.ittlok9wo97FDlALaKaZ8s_ZnDEnVbL0vqa9Pg2Avnql3tiw8qxccqdzL9_Pc5cyNyeYTeqLVmOmPFQxYlJU0w

###
GET http://localhost:8081/users/5f193f6fde32d3373b426f44
Accept: application/json

###
POST http://localhost:8081/login
Content-Type: application/json

{
  "username": "admin",
  "password": "sukenda"
}

###
POST http://localhost:8081/register
Content-Type: application/json

{
  "username": "simak-ma",
  "password": "simak-ma",
  "roles": [
    "ROLE_ADMIN",
    "ROLE_TEACHER"
  ]
}
###
POST http://localhost:8081/refresh-token?token=eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9URUFDSEVSIl0sInN1YiI6InN1a2VuZGEiLCJpYXQiOjE2MDEwMzAzNjEsImV4cCI6MTYwMzkxMDM2MX0.ExDBXhY2KHu5XQgFDhMoX_SRnDZd2kN69K4qMQwqnh5lLIP3S4uBLibx49O5a1GazCURp5vJEn-oZ8zT6oqx8g
Content-Type: application/json
